### ISSUE TITLE
Eric's comment on Facebook re: VisualEditor

### ISSUE THREAD

**Issue by p858snake** [molly/wikimedia-timeline#13]
https://www.facebook.com/groups/wikipediaweekly/permalink/960989863948845/?comment_id=961111543936677&reply_comment_id=961135730600925&comment_tracking=%7B%22tn%22%3A%22R2%22%7D

**Comment by greggrossmeier** [comment]
That's only viewable by those with a FB account, sadly. Up to Molly if she wants that or not.
