### ISSUE TITLE
A friendly note about open sourcing

### ISSUE THREAD

**Issue by idoivri** [molly/wikimedia-timeline#14]
Hey Molly,

Thanks (again!!) for the timeline. It's so beautifully done and helpful :+1: 

If you're looking to open-source your code (which is awesome imho) like you say on your site, you should really consider attaching an open source license (the most widely acceptable permissive license: MIT - see here: https://tldrlegal.com/license/mit-license#fulltext ) with the code. Otherwise the default is that all rights (including copyright and re-use) belong to you.

**Comment by Ironholds** [comment]
Er. [this isn't the MIT](https://github.com/molly/wikimedia-timeline/commit/baf0f0e66e6d7a331632e34f11808fe1e8b5cfc8)?

**Comment by idoivri** [comment]
Oh my, did Imiss that? My bad!!

**Comment by molly** [comment]
No problem!
