### ISSUE TITLE
Add permalinks to individual <h2>'s

### ISSUE THREAD

**Issue by toolness** [molly/wikimedia-timeline#15]
Hello!

I really like the way this page presents information. I also appreciate your efforts to make the wikipedia foundation situation more transparent and understandable.

The one thing I'd add to it is a feature that allows every `<h2>` to be individually permalinked-to via URL fragment.  For example, `http://mollywhite.net/wikimedia-timeline/#1` could specifically link to the first `<h2>` on the page (in this case the "Lila Tretikov announced as Executive Director" section).

This would allow people to mention events at the WMF elsewhere on the net and directly hyperlink them to the wikimedia timeline, so that readers could understand them better in the context of WMF's history and such.

If you think it's a good idea I'd be happy to submit a PR.

**Comment by molly** [comment]
That sounds great!
