### ISSUE TITLE
Factoring out the data

### ISSUE THREAD

**Issue by milimetric** [molly/wikimedia-timeline#16]
I saw your comment about making this mediawiki-friendly.  I have a suggestion for totally over-engineering this :)  If it sounds fun, I will definitely help as I think the effort will be generally useful for timeline visualization on wikis.
1. factor out the data into a yaml or json file which we can store on-wiki (yes storing raw data on wikis is infuriatingly non-standard, we're working on that)
2. create a simple visualization like this one: http://vega.github.io/vega-editor/?mode=vega&spec=lifelines
3. add interactivity using vega-params, like hover to show detail
4. the detail could pop up the nice html descriptions you have, but I'm not 100% sure how to do that through vega, yet, without a gadget or extension or something

I can do 1 - 3 and maybe 4 during a hackathon this spring.

**Comment by molly** [comment]
I would definitely welcome that! It would be pretty great to get rid of a lot of the boilerplate HTML, and I'd love to make timelines like this usable onwiki.

**Comment by milimetric** [comment]
I know I'm moving at the speed of wiki, I don't anticipate I'll go much faster unless there's a hackathon going on.  But I did find more people interested in this: https://phabricator.wikimedia.org/T29156

**Comment by nyurik** [comment]
Awesome timeline, well designed! I don't think graph extension (vega) by itself would be a good tool to show the whole page (you wouldn't want to replace a lot of HTML with one giant image, right?), but it might add useful visualizations in certain spots.

**Comment by milimetric** [comment]
Yes, a basic bare-bones timeline with page-linking would probably be a
first prototype.  And then we could extend vega to allow closer and closer
reproduction of this timeline.
