### ISSUE TITLE
Add links to staff member replies 22 Feb 2016

### ISSUE THREAD

**Issue by Thehelpfulone** [molly/wikimedia-timeline#22]
https://lists.wikimedia.org/pipermail/wikimedia-l/2016-February/082204.html - Faidon
Faidon's title is also probably Principal Technical Operations Engineer per staff page.

https://lists.wikimedia.org/pipermail/wikimedia-l/2016-February/082209.html - Giuseppe

**Comment by molly** [comment]
I've updated Liambotis' title in case you're saying there's an issue there (8567829). But his and Lavagetto's responses are both already included.

**Comment by Thehelpfulone** [comment]
Sorry I meant just to add hyperlinks to the emails as sources like you've done for Erik and Tim.

**Comment by molly** [comment]
Oh! Good point. Done: 4aaabd9

**Comment by Thehelpfulone** [comment]
Great thanks
