### ISSUE TITLE
I like the concept. Question: is everything manually coded, or do you use a framework for editing ?

### ISSUE THREAD

**Issue by Wikinaut** [molly/wikimedia-timeline#26]
See Subject.

**Comment by molly** [comment]
It's manual. I didn't expect it to become such a long timeline; if I'd anticipated it I would have used some sort of templating or static site generator.

**Comment by Wikinaut** [comment]
Well done, I like it and will perhaps "copy" your idea for a timeiine I need.

Potential implementation idea:
- serialize each timeline entry => as json object, event time as key
- store json objects in permanent storage
- render timeline after sorting the p.s. by time
- both methods (static from the source and dynamic from p.s.) could coexists

This could allow online editing, import/export, and editing without actually editing html source.

**Comment by molly** [comment]
Great suggestions! I've been asked by others if I could create something that would generate these for people, so I'll think on it.

**Comment by Wikinaut** [comment]
I _will_ help you. I have a great framework for - saving/retrieving json(sparse arrays) from/to persistent browser storage, and also export/import persistent storage to/from local files, that is my (unpublished) project X.

I will set up a the first version (stripped version X) and based on your present structure. But give me some time (let's say, 5..10 days).

**Comment by RichardAmes** [comment]
A thought:  extend Molly's great effort in both directions --- so it becomes a part of Wikixxxxxx's history.  Generalizing it as a tool is a wonderful idea.

**Comment by Wikinaut** [comment]
@molly 

pre-To-Do-List and something to play with.

I post the following only as an _example_ of the idea of "editing in the browser": see http://multidatespickr.sourceforge.net/#simple-select-min-max-demo : here you _edit_ live the source code and check the results. (Try to change a digit there, e.g. minDate. The field will change to become editable, and you can then click on "test". I like this method.)

The technique could be applied to each time line entry.

All timeline dates should be in UTC and be stored and internally used as Julian dates (I will supply tested JS code for this.) This allows correct timezone independent time calculations, which are often needed.

I want to integrate this with your timeline, and with my previous ideas of saving the changes in the browser storage with the option to save this (in json format or otherwise) to a local file which is important to save a final version (and then to git push, for example).
