### ISSUE TITLE
reason for my departure

### ISSUE THREAD

**Issue by brainwane** [molly/wikimedia-timeline#9]
Thank you for putting together this timeline!

I'm fine with you mentioning that I left and when I left. As part of a pattern involving the quantity of people with certain levels of skills and knowledge leaving WMF, it's relevant. But I would like to explicitly say that my departure really genuinely didn't have anything to do with senior management. I left WMF thinking that it was fine -- in fact, that's a reason I felt okay about deciding to leave a place I cared about so much, because I thought WMF could cope without me. As I perceived it, the new executive director was just settling in and WMF was generally on the right track, iteratively moving closer to reversing the editor decline, with solid management and plans in place to keep positive momentum going, and the conflicts and stumbles from summer 2014 were normal temporary pains, not unusually worrying.

I'm not sure whether or how to reflect that in your document, but I figured it was worth saying in case you want to account for it. Thanks again.

**Comment by molly** [comment]
Thanks for giving me this feedback! It's been a bit weird, trying to decide whose departures and arrivals to include. I'm trying to include people who left or were brought in because of the changes that have happened since Lila's arrival (and not just because they were ready to move on for other reasons), but that's a bit challenging given that most people don't just come out and say that. Perhaps the best thing to do would be to remove your entry.

**Comment by brainwane** [comment]
Molly, thanks for -- as always -- being so thoughtful and systematic about this. I am happy for my entry to be kept (you could add a link to this very discussion if you like) or to be removed. My humble suggestion is: wait a few days and see whether there's anyone else with a somewhat similar request for clarification, so you can deal with them as a group and form a more robust taxonomy.

**Comment by molly** [comment]
Works for me if it works for you! I'll leave this issue open so I remember to revisit it.

**Comment by brainwane** [comment]
Also, yesterday [I publicly blogged](http://www.harihareswara.net/sumana/2016/02/23/0) about the current leadership crisis. In that post I mention that my departure was not a response to the new management, and I speculate on possible outcomes of the current dynamic. If it's useful to you, link away. :)

**Comment by molly** [comment]
You have impeccable timing! :smile: It was on my to-do, though sadly it fell after two rather time-consuming homework assignments. It's in there now!
